.github/workflows/lint-test.yaml
.github/workflows/release.yaml
ct.yaml

We need to setup this in the settings:
https://github.com/helm/chart-releaser-action#pre-requisites
@carlisia

add github action for test/lint/release helm charts

---

charts/velero/Chart.yaml
charts/velero/templates/deployment.yaml
charts/velero/templates/service.yaml

Porting from [PR #16783](https://github.com/helm/charts/pull/16783) on helm/charts repo
This already has a LGTM/approval from @prydonius, and this port indicates my approval. I'm moving this to make up for my tardiness in reviewing and to reduce the burden on external contributors.
Part of #19 
Co-authored-by: Bas Koopmans <github@baskoopmans.nl>
Signed-off-by: Nolan Brubaker <brubakern@vmware.com>

Fix incorect metric scraping on restic pods

---

charts/velero/Chart.yaml
charts/velero/templates/backupstoragelocation.yaml
charts/velero/templates/volumesnapshotlocation.yaml

The backup-location and snapshot-location should be the it's name,
not the provider name. And the provider name should be it's name,
not the name default.
This change enhances after helm install, use `velero backup-location get`
and `velero snapshot-location get`, the NAME and PROVIDER fields are the
user's input.

Correct the location name

---

charts/velero/Chart.yaml
charts/velero/README.md
charts/velero/templates/clusterrole.yaml
charts/velero/templates/clusterrolebinding.yaml
charts/velero/templates/role.yaml
charts/velero/values.yaml

Allows to have a namespaced Velero without cluster admin access or with externally setup ClusterRole.

RBAC: decouple cluster role binding from namespaced role/rolebinding.

---

charts/velero/Chart.yaml
charts/velero/templates/backupstoragelocation.yaml
charts/velero/values.yaml

Allows GCP Workload Identity support in default backup storage location by adding the serviceAccount key in config, as specified here https://github.com/vmware-tanzu/velero-plugin-for-gcp/blob/master/backupstoragelocation.md

Adding support for Workload Identity in backups

---

charts/velero/Chart.yaml
charts/velero/ci/test-values.yaml
charts/velero/crds/backups.yaml
charts/velero/crds/backupstoragelocations.yaml
charts/velero/crds/deletebackuprequests.yaml
charts/velero/crds/downloadrequests.yaml
charts/velero/crds/podvolumebackups.yaml
charts/velero/crds/podvolumerestores.yaml
charts/velero/crds/resticrepositories.yaml
charts/velero/crds/restores.yaml
charts/velero/crds/schedules.yaml
charts/velero/crds/serverstatusrequests.yaml
charts/velero/crds/volumesnapshotlocations.yaml

CRD structural schema had proposal in Velero v1.2.0 release.
But the helm charts did not in sync from Velero.
This cause deploys Velero with helm chart still use the non-structural schema.
Sync CRD manifests with the latest release version v1.3.0-beta.1.

CRD structural schema

---

charts/velero/Chart.yaml
charts/velero/templates/restic-daemonset.yaml

Correct restic daemonset name

---

charts/velero/Chart.yaml
charts/velero/templates/backupstoragelocation.yaml
charts/velero/values.yaml

Add flag _backupsEnabled_ to control whether to create a default backup location or not.
Like velero install `--no-default-backup-location` does.

Support not create a default backup location

---

.github/workflows/lint-test.yaml

The v2 action supports merge commits better, specifically resolving the
`[error]fatal: reference is not a tree` message when re-running a job.
See https://github.com/actions/checkout/issues/23 for more info.
This is currently blocking #71 
Also update the helm chart testing action to rc1
Signed-off-by: Nolan Brubaker <brubakern@vmware.com>

Update github actions

---

ct.yaml

As I understand a new version of `ct` introduced in the [last commit](https://github.com/vmware-tanzu/helm-charts/commit/be130a338420c2a6b12c8a3ac96b7d5e5ff7ea07) uses Helm v3 by default, which has a different `--timeout` argument format:
```
--timeout duration             time to wait for any individual Kubernetes operation (like Jobs for hooks) (default 5m0s)
```
Chart testing will fail like #81 until PR will be merged.
Signed-off-by: Nikolai Iurin <yurinnick93@gmail.com>

Fix timeout chart-testing parameter

---

charts/velero/Chart.yaml
charts/velero/templates/deployment.yaml

This already merged to velero in https://github.com/vmware-tanzu/velero/pull/1893. 
Make helm chart deployment consistent and able to use for vsphere plugin.
Signed-off-by: Chin-Ya Huang <chin-ya.huang@suse.com>

Add LD_LIBRARY_PATH to deployment

---

charts/velero/Chart.yaml
charts/velero/ci/test-values.yaml
charts/velero/crds/backups.yaml
charts/velero/crds/backupstoragelocations.yaml
charts/velero/crds/deletebackuprequests.yaml
charts/velero/crds/downloadrequests.yaml
charts/velero/crds/podvolumebackups.yaml
charts/velero/crds/podvolumerestores.yaml
charts/velero/crds/resticrepositories.yaml
charts/velero/crds/restores.yaml
charts/velero/crds/schedules.yaml
charts/velero/crds/serverstatusrequests.yaml
charts/velero/crds/volumesnapshotlocations.yaml
charts/velero/templates/crds.yaml
charts/velero/templates/crds/backups.yaml
charts/velero/templates/crds/backupstoragelocations.yaml
charts/velero/templates/crds/cleanup-crds.yaml
charts/velero/templates/crds/deletebackuprequests.yaml
charts/velero/templates/crds/downloadrequests.yaml
charts/velero/templates/crds/podvolumebackups.yaml
charts/velero/templates/crds/podvolumerestores.yaml
charts/velero/templates/crds/resticrepositories.yaml
charts/velero/templates/crds/restores.yaml
charts/velero/templates/crds/schedules.yaml
charts/velero/templates/crds/serverstatusrequests.yaml
charts/velero/templates/crds/volumesnapshotlocations.yaml
charts/velero/values.yaml

- Remove `"helm.sh/hook": crd-install` from `crds/*.yaml`
- Copy Helm v2 CRDs to `templates/crds`, gated by `installCRDs` value
Based on [argo-cd](https://github.com/argoproj/argo-helm/tree/master/charts/argo-cd) helm chart.
Closes https://github.com/vmware-tanzu/helm-charts/issues/7.

Make CRDs Helm 3 compatiable

---

charts/velero/Chart.yaml
charts/velero/templates/_helpers.tpl
charts/velero/templates/backupstoragelocation.yaml
charts/velero/templates/volumesnapshotlocation.yaml

- Allow setting different providers for backup/snapshot locations
- Support freeform location configuration to enable 3ed-party providers (OpenEBS, Ceph etc)
- Fix location name setup
[Test output](https://gist.github.com/yurinnick/73beca92c8cf4b72c3d0eb3119456d42)
Signed-off-by: Nikolai Iurin <yurinnick93@gmail.com>

Allow independent backup/snapshot providers

---

charts/velero/Chart.yaml
charts/velero/templates/deployment.yaml
charts/velero/templates/restic-daemonset.yaml
charts/velero/values.yaml

Signed-off-by: Ahmad Haj Ali <ahmad.haj.ali@sap.com>
Pulling images by digest ensures kubernetes cluster does not pull potentially compromised images from the source repository.

[Security] Enable specifying docker image by digest in addition to tag

---

charts/velero/Chart.yaml
charts/velero/templates/_helpers.tpl

Closes https://github.com/vmware-tanzu/helm-charts/issues/95.
Prioritize `configuration.(backupStorageLocation|volumeSnapshotLocation).config` over `configuration.provider`
Signed-off-by: Nikolai Iurin <yurinnick93@gmail.com>

Prioritize location provider over global provider

---

charts/velero/Chart.yaml
charts/velero/ci/test-values.yaml
charts/velero/templates/backupstoragelocation.yaml
charts/velero/templates/volumesnapshotlocation.yaml

This fixes the `toYaml` generation of the template and resolves issue #93, it appears that the release of version 2.9.9 of the chart causes issue with the template generation and the template doesn't seem to render if you use `{{ toYaml .config }}`
This fix actually renders the template locally after removing the `.config`
Fixes https://github.com/vmware-tanzu/helm-charts/issues/93.

Fixing toYaml generation

---

charts/velero/Chart.yaml
charts/velero/templates/deployment.yaml
charts/velero/templates/restic-daemonset.yaml
charts/velero/templates/secret.yaml
charts/velero/values.yaml

This PR adds a new value `credentials.extraEnvVars` allowing to store data in a secret and expose it to the container through an environment variable.
This is necessary for the [Digital Ocean plugin](https://github.com/digitalocean/velero-plugin) and maybe other.
I tested it (and it works). This PR also includes #94 (because without this PR, the chart is broken). I'll rebase when #94 will be merged.
Thanks for this great tool by the way!

Add support for secret env vars

---

.github/workflows/lint-test.yaml
charts/velero/Chart.yaml
charts/velero/crds/backups.yaml
charts/velero/crds/backupstoragelocations.yaml
charts/velero/crds/deletebackuprequests.yaml
charts/velero/crds/downloadrequests.yaml
charts/velero/crds/podvolumebackups.yaml
charts/velero/crds/podvolumerestores.yaml
charts/velero/crds/resticrepositories.yaml
charts/velero/crds/restores.yaml
charts/velero/crds/schedules.yaml
charts/velero/crds/serverstatusrequests.yaml
charts/velero/crds/volumesnapshotlocations.yaml
charts/velero/values.yaml
ct.yaml

1. change target branch from master to main
2. add helm2 & helm3 CI test
3. bump the CRDs manifests sync with velero `v1.4.0`
then #104 is no more needed.

helm 2,3 CI test + Upgrade CRDs to v1.4

---

charts/velero/Chart.yaml
charts/velero/crds/backups.yaml
charts/velero/crds/backupstoragelocations.yaml
charts/velero/crds/deletebackuprequests.yaml
charts/velero/crds/downloadrequests.yaml
charts/velero/crds/podvolumebackups.yaml
charts/velero/crds/podvolumerestores.yaml
charts/velero/crds/resticrepositories.yaml
charts/velero/crds/restores.yaml
charts/velero/crds/schedules.yaml
charts/velero/crds/serverstatusrequests.yaml
charts/velero/crds/volumesnapshotlocations.yaml
charts/velero/templates/crds.yaml

Signed-off-by: Arthur Outhenin-Chalandre <arthur@cri.epita.fr>
I have this issue when I install the latest velero helm chart with ArgoCD:
```
rpc error: code = Unknown desc = Failed to unmarshal manifest: error unmarshaling JSON: Object 'Kind' is missing in '{"apiVersion":"apiextensions.k8s.io/v1beta1"}'
```
ArgoCD recognizes the velero chart as an helm2 chart and therefore uses the helm2 binary for it.
I tested and I saw that the line `apiVersion: apiextensions.k8s.io/v1beta1` is not indented correctly with helm2 (the output in helm3 is correct). This PR is fixing this indentation issue.

Fix Helm 2 CRD generation

---

charts/velero/Chart.yaml
charts/velero/README.md
charts/velero/crds/backups.yaml
charts/velero/crds/backupstoragelocations.yaml
charts/velero/crds/deletebackuprequests.yaml
charts/velero/crds/downloadrequests.yaml
charts/velero/crds/podvolumebackups.yaml
charts/velero/crds/podvolumerestores.yaml
charts/velero/crds/resticrepositories.yaml
charts/velero/crds/restores.yaml
charts/velero/crds/schedules.yaml
charts/velero/crds/serverstatusrequests.yaml
charts/velero/crds/volumesnapshotlocations.yaml
charts/velero/templates/backupstoragelocation.yaml
charts/velero/templates/volumesnapshotlocation.yaml

Fix helm upgrade did not work correctly on BSL and VSL configuration.
```
helm2 install \
--name velero \
--namespace velero \
--set-file credentials.secretContents.cloud=credentials-velero \
--set configuration.provider=aws \
--set configuration.backupStorageLocation.name=default \
--set configuration.backupStorageLocation.bucket=velero \
--set configuration.backupStorageLocation.config.region=minio \
--set configuration.backupStorageLocation.config.s3ForcePathStyle=true \
--set configuration.backupStorageLocation.config.s3Url=http://minio.velero.svc.cluster.local:9000 \
--set initContainers[0].name=velero-plugin-for-aws \
--set initContainers[0].image=velero/velero-plugin-for-aws:v1.1.0 \
--set initContainers[0].volumeMounts[0].mountPath=/target \
--set …
```

fix: helm upgrade did not work correctly on BSL and VSL configuration

---

charts/velero/Chart.yaml
charts/velero/templates/restic-daemonset.yaml

Signed-off-by: Kenny Younger <kyounger@gmail.com>
I don't think there is a reason that the SA should be gated. Existing service accounts should be supported.
Fixes #118

fix: Restic daemonset SA always set, like velero deployment

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature-enhancement-request.md

Provides the Github issue templates to helps us easier to trace the issue with helm chart version and app version, also the installation commands.

Add Github issue template

---

charts/velero/Chart.yaml
charts/velero/README.md
charts/velero/values.yaml

I did not see the CRD changed [from v1.4.0 to v1.4.2](https://github.com/vmware-tanzu/velero/compare/v1.4.0...v1.4.2).
So, we don't need to update the CRDs.

[velero] bump velero version to v1.4.2

---

charts/velero/Chart.yaml
charts/velero/templates/cleanup-crd.yaml

Consider to wrap comment inside to fix error raised by helm 3.3.0:
**Before**
```
velero ➤ helm version                                                                                                                                           git:pr/181
version.BuildInfo{Version:"v3.3.0", GitCommit:"8a4aeec08d67a7b84472007529e8097ec3742105", GitTreeState:"dirty", GoVersion:"go1.14.7"}
velero ➤ helm lint                                                                                                                                              git:pr/181
==> Linting .
[ERROR] templates/cleanup-crd.yaml: object name does not conform to Kubernetes naming requirements: ""
Error: 1 chart(s) linted, 1 chart(s) failed
```
**After**
```
velero ➤ helm version …
```

[velero] Fix helm 3.3.0 lint issue

---

charts/velero/Chart.yaml
charts/velero/ci/test-values.yaml
charts/velero/templates/schedule.yaml
charts/velero/values.yaml

fixes #151
fixes #152
fixes #160
fixes #165
fixes #167

[velero] Add helm annotation for velero.io/v1 schedule CRD

---

.github/workflows/release.yaml

Restrict to run release on upstream repo only, to fixes when developer forks repo `vmware-tanze/helm-charts` that would fail on running CI at the main branch.

[velero] Restrict release on upstream repo

---

charts/velero/Chart.yaml
charts/velero/crds/backups.yaml
charts/velero/crds/backupstoragelocations.yaml
charts/velero/crds/deletebackuprequests.yaml
charts/velero/crds/downloadrequests.yaml
charts/velero/crds/podvolumebackups.yaml
charts/velero/crds/podvolumerestores.yaml
charts/velero/crds/resticrepositories.yaml
charts/velero/crds/restores.yaml
charts/velero/crds/schedules.yaml
charts/velero/crds/serverstatusrequests.yaml
charts/velero/crds/volumesnapshotlocations.yaml
charts/velero/templates/_helpers.tpl
charts/velero/templates/backupstoragelocation.yaml
charts/velero/templates/crds.yaml
charts/velero/templates/schedule.yaml
charts/velero/templates/volumesnapshotlocation.yaml
charts/velero/values.yaml

Create an option in values to disable helm hooks used in CRDs (for Helm v2) and templates manifest (like BackupStorageLocation), introduced in #109 and #153. 
With this change it's possible to install this chart using ArgoCD without any problems, setting the new option to false:
```
enableHelmHooks: false
```
It's possible to disable only CRD hooks or template hooks, in case you don't want to disable both.
The default option is true, which enables all helm hooks.
Helm hooks in crds folder, for Helm v3, are untouched, because they can't be templated.
Fix #158

[velero] Add enable/disable option for helm hooks

---

.github/workflows/release.yml

See https://github.com/helm/chart-releaser-action/issues/13#issuecomment-602063896
The `actions/checkout@v2` by default only fetch HEAD git history, this causes the helm/chart-releaser-action can't fetch the full git history.
fixes #20 

[velero] Fix actions/checkout@v2 does not fetches full git history

---

charts/velero/Chart.yaml
charts/velero/templates/deployment.yaml
charts/velero/templates/restic-daemonset.yaml
charts/velero/values.yaml

This PR enables creation of velero deployment with environment variables configured from secret by using `envFrom.secretRef`. This way of configuration is more secure than configuring environment variables directly with `env` (in case of this repository `credentials.extraEnvVars`).
This was done in order to enable users to securely configure environment variables for clouds such as Openstack, where authentication is most of the time configured differently (env vars) compared to clouds such as AWS, GCP, where secret is mounted from volume.
Example usage:
1. Create secret in velero namespace:
```yaml
---
apiVersion: v1
kind: Secret
metadata:
name: openstack-credentials
namespace: velero
type: Opaque
data:
OS_PROJECT_DOMAIN_NAME: <base64_encoded_value>
OS_USER_DOMAIN_NAME: …
```

[velero] creds env from secret

---

charts/velero/Chart.yaml
charts/velero/templates/schedule.yaml
charts/velero/values.yaml

As with https://github.com/vmware-tanzu/velero/pull/3067, annotations of the schedule get propagated into the backups. This allows us to set annotations on schedules over this chart.
**Attention:** https://github.com/vmware-tanzu/velero/pull/3067 isn't yet released.

[velero] feat(schedule): add annotation templating

---

ct.yaml

the old stable path (https://kubernetes-charts.storage.googleapis.com) does not exist anymore and was replaces to https://charts.helm.sh/stable
our pipeline is pointing to the old one as we can see here: https://github.com/vmware-tanzu/helm-charts/pull/201/checks?check_run_id=1713794402
this PR just set the new path to be used

add stable repo to the new location

---

.github/workflows/lint-test.yaml
charts/velero/Chart.yaml

The previous helm releases (<2.17) had the stable repository hardcoded, the problem is the URL does not exist anymore. 
So using the last helm v2 release 2.17.0 solves the issue.
We use the `chart-testing` to run all tests, in the helm side we are checking if we will release a final `chart-testing` for V2 or not, so in meantime, I've pushed the `chart-testing` image to my quay.io repo and we can use that and unblock the pipeline for v2

[velero] Helm2 fix

---

charts/velero/Chart.yaml
charts/velero/templates/servicemonitor.yaml
charts/velero/values.yaml

This PR adds:
- Ability to deploy ServiceMonitor to another namespace
- Ability to define ServiceMonitor `scrapeTimeout` value

[velero] feat: allow servicemonitor to be deployed in another namespace

---

charts/velero/Chart.yaml
charts/velero/README.md
charts/velero/templates/deployment.yaml

Relates to changes made by [vmware-tanzu/velero PR3447](https://github.com/vmware-tanzu/velero/pull/3447). 
- add `component=velero` label
- remove `--generate-name` and use "velero" as name.
- update documentation

[Velero] Add velero component label and update docs

---

charts/velero/Chart.yaml
charts/velero/templates/deployment.yaml
charts/velero/values.yaml

Signed-off-by: Tareq Sharafy <tareq.sha@gmail.com>
This change allows a users to customize client QPS and burst rate flexibly according to the load in their setups from the chart directly without applying ad-hoc modifications or relying on hard-coded defaults.
Avoid running into performances issues as described in https://github.com/vmware-tanzu/velero/issues/3191

[velero] customize client-qps and client-burst

---

charts/velero/Chart.yaml
charts/velero/templates/deployment.yaml
charts/velero/templates/restic-daemonset.yaml
charts/velero/templates/service.yaml
charts/velero/values.yaml

This PR adds:
Ability to set annotation and label on Velero deployment
Ability to set annotation and label on Restic daemonset
Ability to set annotation and label on velero service

[velero] feat: add annotations for velero deployment and restic daemonset

---

.github/workflows/release.yml

Bump chart-releaser-action to v1.2.0 to fix the index.yaml generated timestamp does not get updated.
Fixes #207

[velero] Bump chart-releaser-action to v1.2.0

---

charts/velero/Chart.yaml
charts/velero/README.md
charts/velero/values.yaml

- Bump Velero version to v1.6.0
- Bump aws example plugin version to v1.2.0

[velero] Bump Velero version to v1.6.0 and plugin version to v1.2.0

---

charts/velero/Chart.yaml
charts/velero/templates/deployment.yaml
charts/velero/values.yaml

To allow the usage of the velero server parameter `--disable-controllers` we need to add a new helm argument.
<sub>Tobias Giese <tobias.giese@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>

[velero] deployment.yaml: add --disable-controllers argument

---

charts/velero/Chart.yaml
charts/velero/templates/volumesnapshotlocation.yaml
charts/velero/values.yaml

According to https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/blob/v1.2.0/velero-plugin-for-microsoft-azure/volume_snapshotter.go#L78, the configuration pass to the plugin would be `map[string]string`. So, we should quote the config key-value pair as string-string, which means always quote the value as `string` type.
The plugin would parse the `string` type to `bool` by themselves https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/blob/v1.2.0/velero-plugin-for-microsoft-azure/volume_snapshotter.go#L139.
~fixes https://github.com/vmware-tanzu/velero/issues/3214~
fixes https://github.com/vmware-tanzu/helm-charts/issues/250

[velero] Fix Azure plugin VSL configuration

---

charts/velero/Chart.yaml
charts/velero/templates/backupstoragelocation.yaml

According to https://github.com/vmware-tanzu/velero-plugin-for-aws/blob/v1.2.0/velero-plugin-for-aws/object_store.go#L87, the configuration pass to the plugin would be `map[string]string`. So, we should quote the config key-value pair as string-string, which means always quote the value as `string` type.
The plugin would parse the `string` type to `bool` by themselves https://github.com/vmware-tanzu/velero-plugin-for-aws/blob/v1.2.0/velero-plugin-for-aws/object_store.go#L127.
fixes #219

[velero] Fix "s3ForcePathStyle" entry gets duplicated with AWS plugin

---

charts/velero/Chart.yaml
charts/velero/README.md
charts/velero/crds/backups.yaml
charts/velero/crds/backupstoragelocations.yaml
charts/velero/crds/deletebackuprequests.yaml
charts/velero/crds/downloadrequests.yaml
charts/velero/crds/podvolumebackups.yaml
charts/velero/crds/podvolumerestores.yaml
charts/velero/crds/resticrepositories.yaml
charts/velero/crds/restores.yaml
charts/velero/crds/schedules.yaml
charts/velero/crds/serverstatusrequests.yaml
charts/velero/crds/volumesnapshotlocations.yaml
charts/velero/templates/backupstoragelocation.yaml
charts/velero/templates/cleanup-crds.yaml
charts/velero/templates/schedule.yaml
charts/velero/templates/upgrade-crds.yaml
charts/velero/templates/volumesnapshotlocation.yaml
charts/velero/values.yaml

Run a _Job_ to apply the CRDs against the Velero container image the user specify.
- On `helm install`, the user might _change_ the velero container image tag, we should update the CRDs to make sure they match against the Velero server.
-  On `helm upgrade`, the velero container image might _upgrade_ to a newer version, we should update the CRDs to make sure they match against the Velero server.
- On `helm rollback`, the velero container image might _downgrade_ to an old version, we should update the CRDs to make sure they match against the Velero server.
Then, we configured these CRs to the cluster (after the applying the CRDs finished):
1. backupstoragelocations.yaml
1. schedules.yaml
1. volumesnapshotlocation.yaml
We _must_ make sure the install/upgrade/rollback CRDs job finished then …

[velero] Fix `helm upgrade` does not upgrade the CRDs

---

.github/auto_assign.yml
.github/workflows/auto_assign_prs.yml
.github/workflows/rebase.yml
charts/velero/Chart.yaml
charts/velero/OWNERS

I'm not contributing too much nowadays for the Velero project and either for the helm chart.
I spoke with @carlisia and told to her that I will step down for now.
Was a great pleasure to be part of this amazing project and help to set up and build this product.
thanks for the trust and the opportunity.
This PR does:
- fix a workflow that had a wrong event name
- cleanup a bit the workflow files
- remove cpanato from the owner file
After we merge this, need to remove me from the collaborator in the repo.
again thanks for everything ❤️ 

[velero] Step down cpanato

---

charts/velero/Chart.yaml
charts/velero/templates/cleanup-crds.yaml
charts/velero/templates/upgrade-crds.yaml
charts/velero/values.yaml

This PR allows the user to customize the upgrade-crds job with labels, annotations and kubectl image.

[velero] Allow better customization for upgrade-crds job

---

charts/velero/Chart.yaml
charts/velero/templates/cleanup-crds.yaml
charts/velero/templates/upgrade-crds.yaml

Signed-off-by: WisdomWolf <wisdomwolf@gmail.com>
As someone who runs a mixed architecture cluster with both ARM and AMD64 devices, I was initially unable to deploy Velero using the helm chart because the Jobs were scheduled to ARM devices which failed.  I added the nodeSelector, tolerations, and affinity sections to the job templates with the same values used in the deployment template.  I confirmed that it worked as expected by deploying the chart locally to my cluster.

[velero] Adds node constraints to job definition

---

charts/velero/Chart.yaml
charts/velero/templates/schedule.yaml
charts/velero/values.yaml

Hi (Olá) guys, since Velero was released in version 1.6.0, we would like to use the field `useOwnerReferencesInBackup`, to avoid Argo CD issues in our deploying process.
Signed-off-by: Caio Almeida <caio.almeida@gympass.com>

[velero] set useOwnerReferencesInBackup to schedule spec if it's set on values

---

.github/workflows/lint-test.yaml
charts/velero/Chart.yaml
charts/velero/templates/schedule.yaml
charts/velero/values.yaml

In multi-layer environment where several values files are applied, it is very useful to allow disabling a schedule that is defined in a common values file.
Reopens https://github.com/vmware-tanzu/helm-charts/pull/208

[velero] allow disabling schedule in value overrides

---

.github/auto-assignees.yml
.github/workflows/lint-test.yaml
charts/velero/Chart.yaml
charts/velero/OWNERS
charts/velero/README.md
charts/velero/crds/backups.yaml
charts/velero/crds/backupstoragelocations.yaml
charts/velero/crds/deletebackuprequests.yaml
charts/velero/crds/downloadrequests.yaml
charts/velero/crds/podvolumebackups.yaml
charts/velero/crds/podvolumerestores.yaml
charts/velero/crds/resticrepositories.yaml
charts/velero/crds/restores.yaml
charts/velero/crds/schedules.yaml
charts/velero/crds/serverstatusrequests.yaml
charts/velero/crds/volumesnapshotlocations.yaml
charts/velero/values.yaml

- Update helm chart minimum Kubernetes version requirement as v1.16.
- Bump CRDs API version to `apiextensions.k8s.io/v1`.
- Bump Velero to v1.6.3 which supports CRDs API version `apiextensions.k8s.io/v1`.
- Bump default kubectl version to `1.16.15`.
- Update helm chart owner/reviewer/maintainer.
fixes #203

[velero] Upgrade CRDs API version to apiextensions.k8s.io/v1

---

charts/velero/Chart.yaml
charts/velero/templates/upgrade-crds.yaml
charts/velero/values.yaml

- The kubectl image tag ordering is `digest -> tag -> cluster Kubernetes version`
- Comment out the `.Values.kubectl.image.tag`, which means that by default the kubectl image tag would be cluster Kubernetes version.
fixes #293

[velero] Use Kubernetes version for kubectl version/tag

---

charts/velero/Chart.yaml
charts/velero/templates/upgrade-crds.yaml

fixes #302
The Kubernetes server version might contain released versions, for example, `1.21.4-gke.301`.
Use the `KubeVersion.Version` would result in the corresponding kubectl image tag can't be pulled.
Change to use `major.minor` version to pull the kubectl image tag.

[velero] Use major.minor version of kubectl image

---

charts/velero/Chart.yaml
charts/velero/templates/cleanup-crds.yaml
charts/velero/templates/upgrade-crds.yaml
charts/velero/values.yaml

This PR allows to define resource requests and limits for the containers in the upgrade and cleanup jobs.
This is necessary in kubernetes clusters where an admission controller prevents the creation of pods without proper resource requests and limits.

[velero] Allow to define resource requests/limits for the containers in the upgrade/cleanup job

---

charts/velero/Chart.yaml
charts/velero/templates/_helpers.tpl
charts/velero/templates/upgrade-crds.yaml

Built-in object `.Capabilities.KubeVersion.Minor` can provide non-number output
For examples:
- on GKE it returns "18+" instead of "18"
- on EKS it returns "20+" instead of "20"
Ref to https://github.com/artifacthub/hub/blob/db0fa6d/charts/artifact-hub/templates/_helpers.tpl#L54-L62
fixes #303

[velero] Fix GKE/EKS with wrong kubectl image tag

---

charts/velero/Chart.yaml
charts/velero/templates/deployment.yaml
charts/velero/templates/restic-daemonset.yaml

Fixes the mistake I introduced in #99, see https://github.com/vmware-tanzu/helm-charts/pull/99#issuecomment-918133171.
All credits to @mshivanna.

[velero] fix extraEnvVars support

---

charts/velero/Chart.yaml
charts/velero/templates/deployment.yaml
charts/velero/values.yaml

Closes #321
Tested locally with success

[velero] Add defaultResticPruneFrequency option to helm chart

---

charts/velero/Chart.yaml
charts/velero/templates/deployment.yaml
charts/velero/values.yaml

A container is a complex structure that itself is usually templated with numerous references to values and other subtemplates. In the values of velero chart `initContainers` is given as a list which means it can't be overridden partially - the whole definition of the init containers must be copied every time a tiny override is needed.
This change allows setting the value of `initContainers` as a string which in turn causes the chart to render it as a template, e.g.:
```yaml
initContainers: |-
- name: myplugin
image: {{ .Values.myplugin.image.repository }}:{{ .Values.myplugin.image.tag }}
resources:
{{- .Values.myplugin.resources | toYaml | nindent 6 }}
...
myplugin:
image:
...
resources:
...
```
and then the init container itself can be customized conveniently by regular values …

[velero] allow setting initContainers as a template

---

charts/velero/Chart.yaml
charts/velero/templates/upgrade-crds.yaml

fix for failing init-container/crd updates
Since velero image is distroles this helmchart uses /tmp volume to host required binaries (sh binary, etc). To populate /tmp volume with relevant binaries kubectl image contents are used: https://github.com/vmware-tanzu/helm-charts/blob/ab1c80e2301d9eb9b07fca399e02e8022612a59b/charts/velero/templates/upgrade-crds.yaml#L46-L50.
This command is failing as it misses args node. It translates in native docker to:
`docker --entrypoint='sh -c 'cp $(which sh) /tmp && cp $(which kubectl) /tmp'  kubectl`
which in consequence produces empty /tmp directory (failed to start container) later required by:
https://github.com/vmware-tanzu/helm-charts/blob/ab1c80e2301d9eb9b07fca399e02e8022612a59b/charts/velero/templates/upgrade-crds.yaml#L66-L70
This leads to …

[velero] fix for failing init-container/crd updates

---

charts/velero/Chart.yaml
charts/velero/values.yaml

When the user uses GCP workload identity, the `credentials.useSecret`
should be false to use workload identity instead of using existing secret.
fixes #242

[velero] Add a comment when to unset credentials.useSecret

---

charts/velero/Chart.yaml
charts/velero/values.yaml

Set useOwnerReferencesInBackup value in values.yaml to false. Due to owner reference between schedule and backups will cause some confusion: https://docs.google.com/document/d/16AE370SDkxtaYEqJwCWEF6neLTPJ8mkC5jyLFjl1KPI/edit
Signed-off-by: Xun Jiang <jxun@vmware.com>

[velero] Update useOwnerReferencesInBackup default value

---

charts/velero/Chart.yaml
charts/velero/templates/backupstoragelocation.yaml
charts/velero/templates/configmaps.yaml
charts/velero/templates/deployment.yaml
charts/velero/templates/restic-daemonset.yaml
charts/velero/templates/role.yaml
charts/velero/templates/rolebinding.yaml
charts/velero/templates/schedule.yaml
charts/velero/templates/secret.yaml
charts/velero/templates/service.yaml
charts/velero/templates/serviceaccount-server.yaml
charts/velero/templates/volumesnapshotlocation.yaml

Hi,
This is "controversial" as some people like not specifying the namespace
on the helm definitions and instead rely on specifying it afterwards
doing a `helm template | kubectl -n foo create -f -`.
However, as some resources definitely need a namespace
(ClusterRoleBinding for example), thus the namespace *needs* to be specified
on both commands `helm template --namespace foo | kubectl -n foo` which
creates redundancy.
In order to be consistent, we specify the `namespace` param on every
resource. This was already the case in the
[charts/velero/templates/update-crds.yaml] file, so we just make it
consistent across every resource.
Signed-off-by: Frank Villaro-Dixon <frank.villaro@infomaniak.com>

[velero] helm: be consistent: add namespace vars everywhere

---

charts/velero/Chart.yaml
charts/velero/templates/extra-manifests.yaml
charts/velero/values.yaml

Signed-off-by: Nick Fisher <nxf5025@gmail.com>
This PR adds the ability to pass extra kubernetes manifests. Even though the chart contains the ability to reference an existing secret it does not allow us to create the secret in the first place using one of the standard K8s secret add-ons such as the following:
- https://github.com/external-secrets/kubernetes-external-secrets
- https://github.com/kubernetes-sigs/secrets-store-csi-driver
This PR will also cover use cases such as when a user is using AAD Pod Identity and they need to set AzureIdentity & AzureIdentityBinding for velero to properly work.
A few other examples of this being implemented on other projects with some good discussions:
- https://github.com/grafana/helm-charts/pull/928
- …

[velero] Added ability to deploy extra K8s manifests

---

charts/velero/Chart.yaml
charts/velero/crds/backups.yaml
charts/velero/crds/backupstoragelocations.yaml
charts/velero/crds/deletebackuprequests.yaml
charts/velero/crds/downloadrequests.yaml
charts/velero/crds/podvolumebackups.yaml
charts/velero/crds/podvolumerestores.yaml
charts/velero/crds/resticrepositories.yaml
charts/velero/crds/restores.yaml
charts/velero/crds/schedules.yaml
charts/velero/crds/serverstatusrequests.yaml
charts/velero/crds/volumesnapshotlocations.yaml
charts/velero/templates/cleanup-crds.yaml

Make the Velero CLI install CRD labels the same as as helm chart install CRD labels.
fix #350

[velero] Remove label `app.kubernetes.io/name: velero` from Velero CRDs

---

charts/velero/Chart.yaml
charts/velero/templates/servicemonitor.yaml

Signed-off-by: Arie Peterson <arie@greenhost.nl>
With this change, the ServiceMonitor is only installed if the corresponding monitoring API is available on the cluster (and the proper helm values are enabled, as before). This way, we can safely enable the servicemonitor in our helm values for velero that are used on many clusters, some of which have the monitoring API/prometheus and some of which do not. The unattractive alternative would be to have some complex mechanism to conditionally set the helm value depending on the cluster configuration.
This is inspired by the [same construct in another helm chart](https://github.com/ory/k8s/blob/master/helm/charts/hydra/templates/service-admin.yaml#L28).

[velero] Only install ServiceMonitor when monitoring API is available

---

charts/velero/Chart.yaml
charts/velero/templates/restic-daemonset.yaml
charts/velero/values.yaml

Adding ability to add environments variables **only** to the Restic daemonset. For example : `GOGC=20`

[velero] Add extra env variables for restic only

---

charts/velero/Chart.yaml
charts/velero/templates/deployment.yaml
charts/velero/templates/restic-daemonset.yaml
charts/velero/values.yaml

Adding ability to set a custom dnsConfig for the pods. Pod's DNS Config field enable users more control on the DNS settings for the pods.
This can help on optimizing DNS search path.

[velero] Add DNSConfig.

---

charts/velero/Chart.yaml
charts/velero/templates/restic-daemonset.yaml
charts/velero/values.yaml

Added affinity to restic daemonset to bring it inline with velero deployment
Developer Certificate of Origin
Version 1.1
Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129
Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.
Developer's Certificate of Origin 1.1
By making a contribution to this project, I certify that:
(a) The contribution was created in whole or in part by me and I
have the right to submit it under the open source license
indicated in the file; or
(b) The contribution is based upon previous work that, to the best
of my knowledge, is covered under an …

[velero] Added affinity to restic

---

charts/velero/Chart.yaml
charts/velero/templates/deployment.yaml
charts/velero/templates/restic-daemonset.yaml
charts/velero/values.yaml

Adds in the ability to specify the termination grace period to the Helm chart. Primary use case is to allow Velero to finish a backup before terminating in case it takes more than the default, previously immutable, 30 seconds to perform a backup.

[velero] Add Termination Grace Period Helm Value

---

charts/velero/Chart.yaml
charts/velero/templates/deployment.yaml

If we're limiting the replica count to a single replica, we should also set the deployment strategy type to "Recreate" to avoid having two instances running, however briefly, at the same time.

[velero] Set Deployment Strategy to Recreate

---

charts/velero/Chart.yaml
charts/velero/templates/deployment.yaml
charts/velero/values.yaml

Signed-off-by: Arthur Burle <arthurburle@gmail.com>
The purpose of this PR is to allow the Chart user to set the flag `garbageCollectionFrequency` to the `velero server` command.

[velero] Adding garbageCollectionFrequency to velero server

---

charts/velero/Chart.yaml
charts/velero/templates/deployment.yaml
charts/velero/values.yaml

Allow users to change namespace in which Velero operates using values.
Signed-off-by: Ondrej Vasko <ondrej.vaskoo@gmail.com>

[velero] Add support to change namespace argument in velero deployment

---

charts/velero/Chart.yaml
charts/velero/templates/deployment.yaml

Signed-off-by: k4mrul <kamrulahsan06@gmail.com>
```
credentials:
extraEnvVars: 
DIGITALOCEAN_TOKEN: do_token  <-- Currently this value is ignored.
```

[velero] use value instead of key for extraEnvVars

---

charts/velero/Chart.yaml
charts/velero/templates/deployment.yaml
charts/velero/values.yaml

Add missing velero server flags.
- --default-backup-storage-location
- --default-backup-ttl
- --default-volume-snapshot-locations
- --metrics-address
- --plugin-dir
- --profiler-address
- --terminating-resource-timeout

[velero] Add missing velero server flags

---

charts/velero/Chart.yaml
charts/velero/values.yaml

Signed-off-by: Ming <mqiu@vmware.com>
Encountered several users who do not know how to skip TLS verification with helm chart installaton, so it's necessary to guide users on how to use it.
Fixes https://github.com/vmware-tanzu/velero/issues/4971

[velero] Add annotation for insecureSkipTLSVerify option

---

charts/velero/Chart.yaml
charts/velero/README.md

[velero] Corrected text for version and wording for Helm 2 support

---

charts/velero/Chart.yaml
charts/velero/templates/deployment.yaml
charts/velero/values.yaml

[velero] support liveness and readiness probes

---

charts/velero/Chart.yaml
charts/velero/templates/deployment.yaml

Fixes https://github.com/vmware-tanzu/helm-charts/issues/470

[velero] probes only when metrics are enabled

---

.github/dependabot.yml

#364
This is the [demo PR](https://github.com/jenting/vmware-tanzu-helm-charts/pull/6).
TODOs:
- Have the CI task to verify the CRD folder in sync
- Bump the chart version (but we could do it manually after the auto PR created)

[velero] Add dependabot file to auto create PR

---

charts/velero/Chart.yaml
charts/velero/templates/prometheusrule.yaml
charts/velero/values.yaml

Similar to existing `podMonitor` and `serviceMonitor` templates, only create the `prometheusRule` if the capabilities are present in the cluster (and rules are defined).

[velero] create prometheusRule only if capabilities are present

---

charts/velero/Chart.yaml
charts/velero/templates/deployment.yaml
charts/velero/values.yaml

You may want to clean up old replicasets so that these don't appear in metrics, OPA violations, ArgoCD UI and so on.
Therefore you want to overwrite the Kubernetes default revision history limit.
See [Kubernetes Clean up Policy](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#clean-up-policy).

[velero] feat: allow changing the default revisionHistoryLimit

---

.github/workflows/lint-test.yaml
charts/velero/Chart.yaml
charts/velero/templates/backupstoragelocation.yaml
charts/velero/templates/schedule.yaml
charts/velero/templates/volumesnapshotlocation.yaml
charts/velero/values.yaml

The PR #414 have moved the upgrade CRD job from post hook to pre hook to ensure that the custom resources create/upgrade after the CRD installed/upgraded.
Therefore, the helm hooks for the custom resources are no longer required includes
- backupstoragelocations.velero.io
- volumesnapshotlocations.velero.io
- schedules.velero.io
Fixes #298 #392 #435 #462
> [!IMPORTANT]
> It's a breaking change during helm upgrade because the backupstoragelocations.velero.io, volumesnapshotlocations.velero.io, schedules.velero.io which were created by helm hooks does not includes the two annotations
> - meta.helm.sh/release-name
> - meta.helm.sh/release-namespace
> 
> Removing the helm hooks, the helm upgrade requires the above two annotations existed.
> The workaround is manually remove the …

[velero] Remove helm hooks for the custom resources

---

charts/velero/Chart.yaml
charts/velero/templates/deployment.yaml
charts/velero/templates/node-agent-daemonset.yaml

There are two ways to enable Prometheus scraping : 
- If using Prometheus Operator, you have to create ServiceMonitors or PodMonitors crds.
- If using Prometheus without Operator, you have to define scraping configuration in pods annotation.
Adding pod scraping annotations and ServiceMonitor (or podMonitor) for the same pod will result to get metrics being collected twice by Prometheus.
This PR intend to add metrics.PodAnnotations only if 'metrics' is enable but metrics.ServiceMonitor and metrics.nodeAgentPodMonitor are **not** enabled.
Fixes #336

[velero] Setting podAnnotations metrics only if not using servicemonitor or podmonitor

---

charts/velero/Chart.yaml
charts/velero/templates/secret.yaml
charts/velero/values.yaml

We use vault webhook to inject the secrets retrieved from [HashiCorp Vault](https://www.hashicorp.com/products/vault) directly into the Pods/Secrets/etc via annotations(https://bank-vaults.dev/docs/mutating-webhook/annotations/).
For e.g:
```
secretAnnotations:
vault.security.banzaicloud.io/vault-serviceaccount: velero
vault.security.banzaicloud.io/vault-role: velero
velero, Secret (v1) has been added:
+ # Source: velero/templates/secret.yaml
+ apiVersion: v1
+ kind: Secret
+ metadata:
+   annotations:
+     vault.security.banzaicloud.io/vault-role: velero
+     vault.security.banzaicloud.io/vault-serviceaccount: velero
+   labels:
+     app.kubernetes.io/instance: velero
+     app.kubernetes.io/managed-by: Helm
+     app.kubernetes.io/name: velero
+     helm.sh/chart: velero-5.1.0
+ …
```

[velero] Add secret annotations

---

.github/workflows/lint-test.yaml
charts/velero/Chart.yaml
charts/velero/templates/deployment.yaml
charts/velero/templates/upgrade-crds/upgrade-crds.yaml
charts/velero/values.yaml

I have added the details in this issue: https://github.com/vmware-tanzu/helm-charts/issues/513
Please take a look.

[velero] Have separate resource usages for velero server pod and upgradeCRDs job pod

---

charts/velero/Chart.yaml
charts/velero/templates/upgrade-crds/upgrade-crds.yaml
charts/velero/values.yaml

This PR allows setting additional templating options for the upgrade CRDs job such as `extraVolumes`, `extraVolumeMounts`, and `extraEnvVars`
fixes: https://github.com/vmware-tanzu/helm-charts/issues/527

[velero] feat: Add additional templating options for Velero upgrade CRDs job

---

charts/velero/Chart.yaml
charts/velero/templates/_helpers.tpl
charts/velero/templates/deployment.yaml
charts/velero/templates/node-agent-daemonset.yaml
charts/velero/templates/secret.yaml
charts/velero/values.yaml

This PR implements to things:
Implement an optional pod trigger, if the secret has been changed. (Fixes https://github.com/vmware-tanzu/velero/issues/5866)
Implement an flag to pass credentials to helm tpl function.

[velero] Pass config trough tpl and implement reload trigger

---

charts/velero/Chart.yaml
charts/velero/templates/upgrade-crds/upgrade-crds.yaml

This makes it possible to add labels to the upgrade-crds job. I used the kubectl.labels value for this, but could change it to a new value to differentiate between jobLabels and podLabels.

[velero] add labels to upgrade-crds job, not only in pod template

---

charts/velero/Chart.yaml
charts/velero/templates/deployment.yaml
charts/velero/values.yaml

This adds the ability to set the default operation timeout, an incredibly small and backwards compatible change that is important for large volume backups via schedules which have no other means to override this option.
resolves https://github.com/vmware-tanzu/helm-charts/issues/545

[velero] Added default operation timeout override

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/lint-test.yaml
.github/workflows/release.yml
RELEASE-INSTRUCT.md

Fix https://github.com/vmware-tanzu/helm-charts/issues/554
- Add helm release instruction document.
- Modify release workflow, make any commit merged into `main` or `velero-helm-charts-v*` trigger helm chart release.
- Modify lint-test, trigger test if the current submit different from the target branch

[velero] Adhere chart to semver

---

charts/velero/Chart.yaml
charts/velero/templates/deployment.yaml
charts/velero/values.yaml

Hi all,
thanks for maintaining this Helm chart. It's a great help in deploying velero.
I came across a use case where I need to add a new flag for the velero server CLI (`--disable-informer-cache` in [1.13](https://github.com/vmware-tanzu/velero/releases/tag/v1.13.0)).
Over time new arguments get added to the velero CLI and I think in general it is helpful to have a generic way of setting these arguments because (for a cluster administrator) it decouples Helm charts upgrades from application (velero) upgrades.
Many other Helm charts implement this pattern as well, e.g. https://github.com/bitnami/charts/blob/9acd313bffb76611d3364b94ed0a7d7e611990d9/bitnami/mariadb/values.yaml#L1115

[velero] Allow passing custom arguments to velero server CLI

---

charts/velero/Chart.yaml
charts/velero/templates/schedule.yaml
charts/velero/values.yaml

I implemented the `paused` flag supported by the Schedule API type so that it can be specified in schedules: in Helm chart's `values.yaml`.
I think this implementation will achieve what was expected in a this issue : #462 .

[velero] Add paused flag for the schedule resource

---

charts/velero/Chart.yaml
charts/velero/templates/backupstoragelocation.yaml
charts/velero/templates/volumesnapshotlocation.yaml
charts/velero/values.yaml

[velero] feat(issue-582): Allow annotating VolumeSnapshotLocation/BackupStorageLocation resources

---

charts/velero/Chart.yaml
charts/velero/templates/serviceaccount-server.yaml
charts/velero/values.yaml

Small fix that allows for use of private registries when using velero datamover.

[velero] feat(issue-584): Adds ImagePullSecrets to Velero server ServiceAccount

---

.idea/.gitignore
charts/velero/Chart.yaml
charts/velero/README.md
charts/velero/crds/backuprepositories.yaml
charts/velero/crds/backups.yaml
charts/velero/crds/backupstoragelocations.yaml
charts/velero/crds/datadownloads.yaml
charts/velero/crds/datauploads.yaml
charts/velero/crds/deletebackuprequests.yaml
charts/velero/crds/downloadrequests.yaml
charts/velero/crds/podvolumebackups.yaml
charts/velero/crds/podvolumerestores.yaml
charts/velero/crds/restores.yaml
charts/velero/crds/schedules.yaml
charts/velero/crds/serverstatusrequests.yaml
charts/velero/crds/volumesnapshotlocations.yaml
charts/velero/values.yaml

[velero] Bump up Velero 1.14.0

---

charts/velero/Chart.yaml
charts/velero/templates/node-agent-daemonset.yaml
charts/velero/values.yaml

Currently, the Helm chart does not allow passing command line parameters such as `--data-mover-prepare-timeout=1h` to the node agent, if I see correctly. This PR adds this option.

[velero] add extraArgs to Velero node agent configuration

---

charts/velero/Chart.yaml
charts/velero/templates/deployment.yaml
charts/velero/values.yaml

Much more user friendly than using extraArgs. Related to changes in velero 1.14. https://velero.io/docs/v1.14/repository-maintenance/#resource-limitation

[velero] feat: Adds resources and limits for repository maintenance job

---

charts/velero/Chart.yaml
charts/velero/templates/deployment.yaml

As written, the chart tries to access `.configuration.repositoryMaintenanceJob.requests.cpu.cpu` and `...memory.memory`, which leads to an error if you actually try to set these values:
```bash
$ helm template velero/velero --version 7.1.2 --set configuration.repositoryMaintenanceJob.requests.cpu=100m
Error: template: velero/templates/deployment.yaml:172:47: executing "velero/templates/deployment.yaml" at <.cpu>: can't evaluate field cpu in type string
Use --debug flag to render out invalid YAML
```
The `limits` values do not have this issue; only the requests.

[velero] Fix maintenance Job resource requests

---

charts/velero/Chart.yaml
charts/velero/values.yaml

- Add `excludedNamespaceScopedResources` to schedules example
- Add `excludedClusterScopedResources` to schedules example
- Add relevant [official document](https://velero.io/docs/v1.14/resource-filtering/#excludes) in `values.yaml`
No values code changes, only changes commented example values

[velero] Add example excluded-resources values

---

charts/velero/Chart.yaml
charts/velero/templates/schedule.yaml

The `charts/velero/templates/schedule.yaml` will always render the annotations section even if there is no values defined, which will bring following meaningless result:
```diff
kind: Schedule
metadata:	
+  annotations: null
```
And many tools like argo-cd will treat it as diff, so we should only render annotations only if present in values.

[velero] fix: render schedule annotations only if present in values

---

charts/velero/Chart.yaml
charts/velero/templates/deployment.yaml
charts/velero/templates/schedule.yaml

This PR adds the Kubernetes-recommended label "app.kubernetes.io/version" to the Deployment and its Pods.
https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels
The value of the version label:
> The current version of the application (e.g., a [SemVer 1.0](https://semver.org/spec/v1.0.0.html), revision hash, etc.)

[velero] Add version label to deployment

---

charts/velero/Chart.yaml
charts/velero/templates/node-agent-daemonset.yaml
charts/velero/values.yaml

The velero cli had the support for [block volumes ](https://github.com/vmware-tanzu/velero/pull/6680).
This support was not present in velero helm, refer [here ](https://github.com/vmware-tanzu/velero/issues/7947#issuecomment-2219849688).
This PR add the support in Helm charts for velero

[velero] Fix: support for block volumes in velero helm

---

charts/velero/Chart.yaml
charts/velero/templates/NOTES.txt

This PR fixes a bug that occurred while templating charts/velero/tempaltes/NOTES.txtwhen when using custom ConfigMaps in the values file. 
- No changes to variables

[velero] Fix/notes template

---

charts/velero/Chart.yaml
charts/velero/templates/deployment.yaml
charts/velero/values.yaml

this PR add support for `pod.spec.runtimeClass` field support of velero deployment

[velero] add runtimeClassName for pod.spec.runtimeClassName

---

charts/velero/Chart.yaml
charts/velero/templates/node-agent-daemonset.yaml

Indendation of the dnsConfig was wrong. Should be on the same level as dnsPolicy.

[velero] Correct indent of dnsConfig in daemonset

---

charts/velero/Chart.yaml
charts/velero/templates/node-agent-daemonset.yaml

This PR fixes issue [659](https://github.com/vmware-tanzu/helm-charts/issues/659)

[velero] fix node-agent-daemonset

---

charts/velero/Chart.yaml
charts/velero/templates/_helpers.tpl

This PR fix a missing helper for `.Values.runtimeClass`, this new fields was implemented in https://github.com/vmware-tanzu/helm-charts/pull/656

[velero] fix: Add missing helper for .Values.runtimeClassName

---

.github/auto-assignees.yml

[velero] remove qiuming-best from maintainers

---

charts/velero/Chart.yaml
charts/velero/templates/_helpers.tpl
charts/velero/templates/node-agent-daemonset.yaml
charts/velero/values.yaml

This PR add support for pod.spec.runtimeClass field support of velero node-agent

[velero] add runtimeClassName for node-agent

---

charts/velero/Chart.yaml
charts/velero/crds/backuprepositories.yaml
charts/velero/crds/backups.yaml
charts/velero/crds/backupstoragelocations.yaml
charts/velero/crds/datadownloads.yaml
charts/velero/crds/datauploads.yaml
charts/velero/crds/deletebackuprequests.yaml
charts/velero/crds/downloadrequests.yaml
charts/velero/crds/podvolumebackups.yaml
charts/velero/crds/podvolumerestores.yaml
charts/velero/crds/restores.yaml
charts/velero/crds/schedules.yaml
charts/velero/crds/serverstatusrequests.yaml
charts/velero/crds/volumesnapshotlocations.yaml

[velero] fix crd: creationTimestamp expected string, but got null

---

charts/velero/Chart.yaml
charts/velero/templates/deployment.yaml
charts/velero/templates/node-agent-daemonset.yaml
charts/velero/templates/upgrade-crds/upgrade-crds.yaml
charts/velero/values.yaml

This PR aims to resolve https://github.com/vmware-tanzu/helm-charts/issues/633
This PR contains the following changes:
- Updated values.yaml to accept list as input for extraEnvVars instead of key/value dictionary. This will allow user to input environment variables in all accepted formats by kubernetes
- Templates modified to accommodate the new input type for extraEnvVars

[velero] allow extraEnvVars to accept all formats of environment variable declaration

---

charts/velero/Chart.yaml
charts/velero/templates/node-agent-daemonset.yaml
charts/velero/values.yaml

[velero] feat(node-agent): expose data-mover-prepare-timeout in helm chart

---

charts/velero/Chart.yaml
charts/velero/templates/deployment.yaml
charts/velero/templates/node-agent-daemonset.yaml
charts/velero/values.yaml

This PR aims to address the feature enhancement request given under https://github.com/vmware-tanzu/helm-charts/issues/556
The following changes are present in the PR:
- Conditional hostAliases block added under spec.template.spec for velero deployment and node-agent daemonset
- Optional hostAliases field in values.yaml added for velero deployment and node-agent daemonset

[velero] add support for adding hostAliases to deployment and daemonset

---

charts/velero/Chart.yaml
charts/velero/templates/service.yaml
charts/velero/values.yaml

Adding traffic policy to metrics service with External/Internal setting and service type with ClusterIP/NodePort, this feature is very helpful if monitoring metrics  is from a different cluster.

[Velero] Add traffic policy and type for metrics service

---

charts/velero/Chart.yaml
charts/velero/templates/deployment.yaml
charts/velero/templates/serviceaccount-server.yaml
charts/velero/templates/upgrade-crds/serviceaccount-upgrade.yaml

In serviceaccount and deployment there are extra space : 
```
HOOKS:
---
apiVersion: v1
kind: ServiceAccount
metadata:
name: velero-server-upgrade-crds
namespace: velero
annotations:
"helm.sh/hook": pre-install,pre-upgrade,pre-rollback
"helm.sh/hook-weight": "-4"
"helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
cluster: dev
labels:
app.kubernetes.io/name: velero
app.kubernetes.io/instance: velero
app.kubernetes.io/managed-by: Helm
helm.sh/chart: velero-10.0.1
automountServiceAccountToken: true
---
```
```
MANIFEST:
---
apiVersion: v1
kind: ServiceAccount
metadata:
name: velero-server
namespace: velero
annotations:
cluster: dev
labels:
app.kubernetes.io/name: velero
app.kubernetes.io/instance: velero
app.kubernetes.io/managed-by: Helm
helm.sh/chart: velero-10.0.1 …
```

[velero] Fix syntax bug in deployment and service account

---

charts/velero/Chart.yaml
charts/velero/templates/deployment.yaml
charts/velero/templates/node-agent-daemonset.yaml

I'm having issues when adding and not adding `hostAliases` :
In the case of not adding `hostAliases` there is extra space on `node-agent daemonset` :
```
name: node-agent
role: node-agent
app.kubernetes.io/name: velero
app.kubernetes.io/instance: velero
app.kubernetes.io/managed-by: Helm
helm.sh/chart: velero-10.0.4
annotations:
prometheus.io/path: /metrics
prometheus.io/port: "8085"
prometheus.io/scrape: "true"
spec:
serviceAccountName: velero-server
automountServiceAccountToken: true
```
And in the case of adding `hostAliases` there is error on `velero deployment` :
`YAML parse error on velero/templates/deployment.yaml: error converting YAML to JSON: yaml: line 35: did not find expected key`

[velero] Fix syntax bug in hostAliases

---

charts/velero/Chart.yaml
charts/velero/values.yaml

The provided example shall never be one that gives false negatives on the subject of whether a backup is failing. The consequences may be catastrophic if someone does not notice it is an absolutely horrible example that is giving a false sense of security.
It would be better to remove the example altogether than to provide one that can keep claiming everything is in order when there is a chain of failed backups instead.
If it is impossible to include mine / another one that actually works, please remove the bad example that the helm chart's `values.yaml` currently provides

[velero] Update example PrometheusRule

---

charts/velero/Chart.yaml
charts/velero/templates/deployment.yaml
charts/velero/templates/node-agent-daemonset.yaml
charts/velero/values.yaml

Add support for container resource [resizePolicy](https://kubernetes.io/docs/tasks/configure-pod-container/resize-container-resources/) configuration in Deployment and DaemonSet workloads. This allows users to specify how containers should handle resource limit updates (CPU/memory) without requiring pod restarts.
This feature improves workload availability by allowing in-place resource updates for compatible applications, reducing downtime during resource adjustments.

[velero] feat: Support in-place resource resize for containers

---

charts/velero/Chart.yaml
charts/velero/values.yaml

This pull request is a short term solution as bitnami will delete images from actual repository `docker.io/bitnami` and we have to migrate to `docker.io/bitnamilegacy` before September the 29th (see [here](https://community.broadcom.com/tanzu/blogs/beltran-rueda-borrego/2025/08/18/how-to-prepare-for-the-bitnami-changes-coming-soon)).
I have made another [pull request](https://github.com/vmware-tanzu/helm-charts/pull/706) which is better for the future and `kubectl` image updates.
But it depends of this [pull request](https://github.com/vmware-tanzu/velero/pull/9132) and I'm not sure everything will be merged before September the 29th.

[velero] Move to bitnamilegacy

---

charts/velero/Chart.yaml
charts/velero/values.schema.json

[The deployment template](https://github.com/vmware-tanzu/helm-charts/blob/3d2d76e399488a7674ce4ade8b350932b86a9b08/charts/velero/templates/deployment.yaml#L289) supports strings as well as arrays/null, therefore the string type should be included in the values schema.

[velero] correct initContainer value json schema

---

charts/velero/Chart.yaml
charts/velero/crds/backuprepositories.yaml
charts/velero/crds/backups.yaml
charts/velero/crds/datauploads.yaml
charts/velero/crds/podvolumebackups.yaml
charts/velero/crds/podvolumerestores.yaml
charts/velero/crds/schedules.yaml
charts/velero/templates/NOTES.txt
charts/velero/templates/deployment.yaml
charts/velero/values.yaml

Updated image and crds to velero 1.17.0
fixes https://github.com/vmware-tanzu/helm-charts/issues/679

[velero] Update velero to v1.17.0
