vmware-tanzu/helm-charts

CODE-OF-CONDUCT.md, CONTRIBUTING.md
=> Add contributor and CoC info

README.md
=> remove comment from readme

charts/velero/Chart.yaml, charts/velero/templates/backupstoragelocation.yaml, charts/velero/templates/volumesnapshotlocation.yaml, charts/velero/values.yaml
Port of https://github.com/helm/charts/pull/17585
Part of #19 
The previous PR did _not_ have any approvals. However, this port serves as my approval.
=> Add support for cross-subscription backups/restore (Azure)

.github/workflows/PULL_REQUEST_TEMPLATE.md
=> [general] Add PR template

charts/velero/Chart.yaml, charts/velero/templates/deployment.yaml, charts/velero/templates/restic-daemonset.yaml
fix issue [#2125](https://github.com/vmware-tanzu/velero/issues/2152), depend on PR[#2166](https://github.com/vmware-tanzu/velero/pull/2166)
Signed-off-by: haoshuwei <haoshuwei24@gmail.com>
=> add alibabacloud provider env

charts/velero/Chart.yaml, charts/velero/templates/cleanup-crds.yaml
=> Update cleanup CRDs label name

.github/workflows/lint-test.yaml, .github/workflows/release.yaml
=> update GH actions

charts/velero/Chart.yaml, charts/velero/templates/restic-daemonset.yaml
=> [velero] Add custom env variables to Restic

charts/velero/Chart.yaml, charts/velero/templates/restic-daemonset.yaml
There is no provider called `mino`, so remove it.
=> Remove provider minio

charts/velero/Chart.yaml, charts/velero/templates/deployment.yaml, charts/velero/templates/restic-daemonset.yaml, charts/velero/values.yaml
Closes #34 
@carlisia I have also added the securityContext to restic, as you mention in #41
=> Add securityContext to deployment

charts/velero/Chart.yaml, charts/velero/README.md, charts/velero/values.yaml
=> Bump velero version v1.3.0 and plugin version v1.0.1

charts/velero/Chart.yaml, charts/velero/README.md, charts/velero/values.yaml
Signed-off-by: Nolan Brubaker <brubakern@vmware.com>
=> Bump chart for Velero v1.3.1

charts/velero/Chart.yaml, charts/velero/values.yaml
=> Update velero-restic-restore-helper image path

charts/velero/Chart.yaml, charts/velero/README.md
=> Update docs for Helm 3

charts/velero/Chart.yaml, charts/velero/templates/deployment.yaml, charts/velero/templates/restic-daemonset.yaml, charts/velero/values.yaml
Signed-off-by: Ashish Amarnath <ashisham@vmware.com>
Fixes: #105
=> Feature flags in helm charts

charts/velero/Chart.yaml, charts/velero/OWNERS
~This repo doesn't rely on bots to manage permissions, so this because
obsolete.~
Clean up perm related files. Since the linter won't let us delete the OWNERS file.
=> Update OWNERS file

.github/workflows/PULL_REQUEST_TEMPLATE.md, .github/workflows/release.yaml, README.md
=> Address insensitive language

charts/velero/Chart.yaml, charts/velero/README.md, charts/velero/values.yaml
=> Update documentation for 1.4

charts/velero/Chart.yaml, charts/velero/OWNERS
=> + jenting / - skriss

charts/velero/Chart.yaml, charts/velero/README.md
=> Fix set-file credentials

charts/velero/Chart.yaml, charts/velero/templates/deployment.yaml, charts/velero/values.yaml
Signed-off-by: Christian Kotzbauer <christian.kotzbauer@gmail.com>
=> add affinity option to velero deployment

.github/workflows/rebase.yml
=> Add an auto-rebase workflow

.github/workflows/lint-test.yaml, .github/workflows/release.yaml
- Update actions to use release 1.0.0
- update helm 2 to release 2.16.9
=> actions: update helm actions to use release 1.0.0

README.md, index.md
- update readme
- update link in the index.md to use the main branch instead of the master
Fixes: https://github.com/vmware-tanzu/helm-charts/issues/132
note: let me know if there are more things to update
=> Update GH-pages branch

.github/PULL_REQUEST_TEMPLATE.md
=> fix: pull request template not working

charts/velero/Chart.yaml, charts/velero/templates/backupstoragelocation.yaml, charts/velero/values.yaml
=> fix: custom CA not working

charts/velero/Chart.yaml, charts/velero/templates/deployment.yaml, charts/velero/templates/restic-daemonset.yaml, charts/velero/values.yaml
Signed-off-by: Armin <armin@coralic.nl>
=> [velero] Adding imagePullSecrets to the chart

CODE-OF-CONDUCT.md, charts/velero/Chart.yaml, charts/velero/README.md, charts/velero/crds/backups.yaml, charts/velero/crds/backupstoragelocations.yaml, charts/velero/crds/deletebackuprequests.yaml, charts/velero/crds/downloadrequests.yaml, charts/velero/crds/podvolumebackups.yaml, charts/velero/crds/podvolumerestores.yaml, charts/velero/crds/resticrepositories.yaml, charts/velero/crds/restores.yaml, charts/velero/crds/schedules.yaml, charts/velero/crds/serverstatusrequests.yaml, charts/velero/crds/volumesnapshotlocations.yaml, charts/velero/templates/deployment.yaml, charts/velero/values.yaml
=> [velero] Bump Velero version to v1.5.1

charts/velero/Chart.yaml, charts/velero/templates/serviceaccount-server.yaml
Signed-off-by: Michael Fornaro <20387402+xUnholy@users.noreply.github.com>
Fixing bug as mentioned in #161 
=> [velero] fix bug using workload identity issue #161

charts/velero/Chart.yaml, charts/velero/templates/deployment.yaml, charts/velero/templates/restic-daemonset.yaml
=> [Velero] Fixing restic daemonset yaml

charts/velero/Chart.yaml, charts/velero/values.yaml
Just to make it official, so we cannot drop it silently.
=> [velero] Add priorityClassName in the values.yaml file to make it 'official'

charts/velero/Chart.yaml, charts/velero/values.yaml
Signed-off-by: mukul.garg <mukul.garg@ymail.com>
=> [velero] Correct syntax of iam role pod annotation in values.yaml

charts/velero/Chart.yaml, charts/velero/values.yaml
Signed-off-by: Nolan Brubaker <brubakern@vmware.com>
=> Bump Velero version to v1.5.2

.github/auto_assign.yml, .github/workflows/auto_assign_prs.yml
=> Add auto-assign reviewers GH action

.github/workflows/release.yaml
fixes #20 
reference to https://github.com/helm/chart-releaser-action/tree/v1.0.0#example-workflow
=> [velero] Release helm charts by github-actions

charts/velero/Chart.yaml, charts/velero/templates/deployment.yaml, charts/velero/templates/restic-daemonset.yaml, charts/velero/values.yaml
Just something I needed to set!
=> [velero] Support setting dnsPolicy on restic daemonset and velero deployment

charts/velero/Chart.yaml, charts/velero/templates/restic-daemonset.yaml
fixes https://github.com/vmware-tanzu/helm-charts/issues/189
=> [velero] fixed dnsPolicy position in yaml definition

charts/velero/Chart.yaml, charts/velero/README.md
=> [velero] Use image tag 1.5 instead of 1.5.x

charts/velero/Chart.yaml, charts/velero/values.yaml
=> [velero] Add doc on how to include secrets in values.yaml

.github/PULL_REQUEST_TEMPLATE.md, charts/velero/Chart.yaml, charts/velero/README.md, charts/velero/templates/service.yaml, charts/velero/templates/servicemonitor.yaml, charts/velero/values.yaml
fixes #195 
this revert #131 
we could revisit #136
=> [velero] Revert "Remove Prometheus operator CRDs"

charts/velero/Chart.yaml, charts/velero/values.yaml
=> [velero] Bump velero version v1.5.3

charts/velero/Chart.yaml, charts/velero/templates/restic-daemonset.yaml, charts/velero/values.yaml
Signed-off-by: Peter Ekhator <peterekhator@gmail.com>
=> [velero] feat: add nodeselector for restic

charts/velero/Chart.yaml
=> [velero] Update chart maintainer

.github/workflows/lint-test.yaml, charts/velero/Chart.yaml, charts/velero/README.md, charts/velero/ci/test-values.yaml, charts/velero/templates/_helpers.tpl, charts/velero/templates/backupstoragelocation.yaml, charts/velero/templates/cleanup-crd.yaml, charts/velero/templates/crds.yaml, charts/velero/templates/schedule.yaml, charts/velero/templates/volumesnapshotlocation.yaml, charts/velero/values.yaml
=> [velero] Helm v2 deprecated

charts/velero/Chart.yaml, charts/velero/templates/serviceaccount-server.yaml, charts/velero/values.yaml
=> [velero] Add labels to service account

charts/velero/Chart.yaml, charts/velero/crds/backups.yaml, charts/velero/crds/backupstoragelocations.yaml, charts/velero/crds/deletebackuprequests.yaml, charts/velero/crds/downloadrequests.yaml, charts/velero/crds/podvolumebackups.yaml, charts/velero/crds/podvolumerestores.yaml, charts/velero/crds/resticrepositories.yaml, charts/velero/crds/restores.yaml, charts/velero/crds/schedules.yaml, charts/velero/crds/serverstatusrequests.yaml, charts/velero/crds/volumesnapshotlocations.yaml
=> Sync Velero v1.6.0 CRDs

charts/velero/Chart.yaml, charts/velero/values.yaml
=> [velero] Sets default resource requests and limits

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature-enhancement-request.md
=> [velero] Remove helm2 from issue template

charts/velero/Chart.yaml, charts/velero/ci/test-values.yaml, charts/velero/templates/backupstoragelocation.yaml, charts/velero/values.yaml
=> [velero] Configure default BackupStorageLocation (BSL)

.github/auto-assignees.yml, .github/auto_assign.yml, .github/workflows/auto_assign_prs.yml, .github/workflows/auto_request_review.yml, charts/velero/Chart.yaml
Signed-off-by: Carlisia <carlisia@grokkingtech.io>
=> [velero] Update auto assign of reviewers

charts/velero/Chart.yaml, charts/velero/templates/deployment.yaml
Signed-off-by: Norwin Schnyder <norwin.schnyder+github@gmail.com>
Align the if-else logic of `volumes` and `volumeMounts`:
```
volumes:
{{- if .Values.credentials.useSecret }}
- name: cloud-credentials
secret:
secretName: {{ include "velero.secretName" . }}
{{- end }}
- name: plugins
emptyDir: {}
- name: scratch
emptyDir: {}
```
```
volumeMounts:
- name: plugins
mountPath: /plugins
{{- if .Values.credentials.useSecret }}
- name: cloud-credentials
mountPath: /credentials
{{- end }}
- name: scratch
mountPath: /scratch
```
=> [velero] Fix scratch volume mount

charts/velero/Chart.yaml, charts/velero/values.yaml
=> [velero] Bump version v1.6.1

charts/velero/Chart.yaml, charts/velero/templates/backupstoragelocation.yaml
=> [velero] Quote string

charts/velero/Chart.yaml, charts/velero/OWNERS
=> [velero] Update owners

charts/velero/Chart.yaml, charts/velero/values.yaml
Bump default Velero version to v1.6.2
=> [velero] Bump Velero version v1.6.2

charts/velero/Chart.yaml, charts/velero/README.md
=> [velero] docs: fix helm 3 argument order

charts/velero/Chart.yaml, charts/velero/values.yaml
=> [velero] Since velero-plugin-for-csi and features=EnableCSI are required to enable velero-plugin-for-aws, I added them to the comments for clarity.

charts/velero/Chart.yaml, charts/velero/ci/test-values.yaml
=> [velero] Deploy restic DaemonSet in CI test

charts/velero/Chart.yaml, charts/velero/values.yaml
=> [velero] Bump velero to v1.7.1

charts/velero/Chart.yaml, charts/velero/templates/cleanup-crds.yaml, charts/velero/templates/upgrade-crds.yaml, charts/velero/values.yaml
Signed-off-by: Nick Fisher <nxf5025@gmail.com>
Adding container & pod security context to the upgrade/cleanup crd resources
=> [velero] Adding security contexts for crds

charts/velero/Chart.yaml, charts/velero/OWNERS, charts/velero/README.md, charts/velero/crds/backups.yaml, charts/velero/crds/backupstoragelocations.yaml, charts/velero/crds/deletebackuprequests.yaml, charts/velero/crds/downloadrequests.yaml, charts/velero/crds/podvolumebackups.yaml, charts/velero/crds/podvolumerestores.yaml, charts/velero/crds/resticrepositories.yaml, charts/velero/crds/restores.yaml, charts/velero/crds/schedules.yaml, charts/velero/crds/serverstatusrequests.yaml, charts/velero/crds/volumesnapshotlocations.yaml, charts/velero/values.yaml
=> [velero] Bump velero v1.8.0

charts/velero/Chart.yaml, charts/velero/values.yaml
=> [velero] Velero v1.8.1

.github/auto-assignees.yml, charts/velero/Chart.yaml, charts/velero/templates/deployment.yaml, charts/velero/templates/restic-daemonset.yaml
=> [velero] Quote value

charts/velero/Chart.yaml, charts/velero/templates/clusterrolebinding.yaml, charts/velero/values.yaml
=> [velero] Support customize overwrite the cluster administrator (ClusterRole) name

charts/velero/Chart.yaml, charts/velero/templates/backupstoragelocation.yaml, charts/velero/values.yaml
Signed-off-by: Robert Batson <robert.batsonjr@gmail.com>
=> [velero] add support for accessMode to BackupStorageLocation

.github/workflows/lint-test.yaml, charts/velero/Chart.yaml
=> [velero] Update CI GitHub action

.github/auto-assignees.yml, .github/workflows/lint-test.yaml
Signed-off-by: Scott Seago <sseago@redhat.com>
=> Add Shubham to auto-assignees

charts/velero/Chart.yaml, charts/velero/README.md, charts/velero/crds/backups.yaml, charts/velero/crds/backupstoragelocations.yaml, charts/velero/crds/deletebackuprequests.yaml, charts/velero/crds/downloadrequests.yaml, charts/velero/crds/podvolumebackups.yaml, charts/velero/crds/podvolumerestores.yaml, charts/velero/crds/resticrepositories.yaml, charts/velero/crds/restores.yaml, charts/velero/crds/schedules.yaml, charts/velero/crds/serverstatusrequests.yaml, charts/velero/values.yaml
=> [velero] Velero v1.9.0

charts/velero/Chart.yaml
We forget to bump the appVersion to 1.9.0.
=> [velero] Bump app version to 1.9.0

charts/velero/Chart.yaml, charts/velero/templates/deployment.yaml, charts/velero/values.yaml
Signed-off-by: Tambet Liiv <tambet@liiv.eu>
Flag itself added in https://github.com/vmware-tanzu/velero/pull/3823.
=> [velero] add option to set --client-page-size

charts/velero/Chart.yaml, charts/velero/templates/deployment.yaml, charts/velero/values.yaml
Signed-off-by: flbla<flbla@users.noreply.github.com>
=> [velero] add storeValidationFrequency parameter

charts/velero/Chart.yaml, charts/velero/crds/backups.yaml, charts/velero/crds/schedules.yaml, charts/velero/values.yaml
=> [velero] v1.9.1

charts/velero/Chart.yaml, charts/velero/templates/prometheusrule.yaml, charts/velero/values.yaml
Rules borrowed from https://github.com/vmware-tanzu/velero/issues/2725#issuecomment-661577500
Closes #365.
Signed-off-by: Philipp Born <git@pborn.eu>
=> [velero] add prometheusRule

.github/workflows/lint-test.yaml
[velero] Add Kubernetes 1.25 CI test
=> [velero] Add Kubernetes 1.25 CI test

charts/velero/Chart.yaml, charts/velero/templates/deployment.yaml, charts/velero/templates/restic-daemonset.yaml, charts/velero/values.yaml
=> [velero] Add support for Container Lifecycle Hooks

charts/velero/Chart.yaml, charts/velero/templates/servicemonitor.yaml, charts/velero/values.yaml
Signed-off-by: garcia.ryan <garcia.ryan@solute.us>
Closes #403
=> [velero] Adding scheme and tlsConfig values to serviceMonitor template

charts/velero/Chart.yaml, charts/velero/crds/downloadrequests.yaml, charts/velero/values.yaml
=> [velero] v1.9.2

charts/velero/Chart.yaml, charts/velero/crds/restores.yaml, charts/velero/values.yaml
=> [velero] Bump velero version to v1.9.3

charts/velero/Chart.yaml, charts/velero/templates/servicemonitor.yaml, charts/velero/values.yaml
=> [velero] ServiceMonitor annotations

charts/velero/Chart.yaml, charts/velero/templates/servicemonitor.yaml, charts/velero/values.yaml
=> [velero] fix: remove check on CRDs availability

.github/auto-assignees.yml, charts/velero/Chart.yaml, charts/velero/OWNERS, charts/velero/values.yaml
=> [velero] Bump velero version v1.10.2

charts/velero/Chart.yaml, charts/velero/README.md, charts/velero/crds/backups.yaml, charts/velero/crds/downloadrequests.yaml, charts/velero/crds/restores.yaml, charts/velero/crds/schedules.yaml, charts/velero/values.yaml
=> [velero] Bump velero version v1.11.0

charts/velero/Chart.yaml, charts/velero/README.md, charts/velero/templates/deployment.yaml, charts/velero/templates/node-agent-daemonset.yaml
=> [velero] Fix no velero deployment

charts/velero/Chart.yaml, charts/velero/values.yaml
=> [velero] doc: the configuration.provider is deprecated

charts/velero/Chart.yaml, charts/velero/values.yaml
Signed-off-by: Ugur Can Ozturk [ugurozturk918@gmail.com](mailto:ugurozturk918@gmail.com)
I thought it might be a good idea to drop a note about the `restore-wait` container hardening options. This would be particularly helpful for teams using restricted pod security standards if they were looking for a way to manipulate those specs.
=> [velero] improvement values yaml references for fs-restore-action-config

charts/velero/Chart.yaml, charts/velero/templates/backupstoragelocation.yaml, charts/velero/values.yaml
Documentation: https://velero.io/docs/main/api-types/backupstoragelocation/
Documentation: https://velero.io/docs/main/api-types/backupstoragelocation/
=> [velero] Support setting `validationFrequency` in `BackupStorageLocation`

charts/velero/Chart.yaml, charts/velero/templates/servicemonitor.yaml, charts/velero/values.yaml
=> [velero]: feature to allow relabelings in `serviceMonitor`

charts/velero/Chart.yaml, charts/velero/templates/backupstoragelocation.yaml, charts/velero/templates/schedule.yaml, charts/velero/templates/volumesnapshotlocation.yaml, charts/velero/values.yaml
On some environments, the helm hook annotations are not necessary. For example, if the CRDs are handled outside of this helm chart.
=> [velero] Add toggle to disable annotations

charts/velero/Chart.yaml, charts/velero/templates/volumesnapshotlocation.yaml, charts/velero/values.yaml
=> Add credential configuration for VSL

charts/velero/Chart.yaml, charts/velero/templates/deployment.yaml, charts/velero/values.yaml
Should fix [https://github.com/vmware-tanzu/helm-charts/issues/516](https://github.com/vmware-tanzu/helm-charts/issues/516)
=> [velero] Add option to use --default-snapshot-move-data

.github/workflows/release.yml
closes https://github.com/vmware-tanzu/helm-charts/issues/521
=> [velero]: Feature push new charts to GHCR OCI registry as well

charts/velero/Chart.yaml, charts/velero/README.md, charts/velero/ci/test-values.yaml, charts/velero/crds/backups.yaml, charts/velero/crds/datadownloads.yaml, charts/velero/crds/datauploads.yaml, charts/velero/crds/downloadrequests.yaml, charts/velero/crds/podvolumebackups.yaml, charts/velero/crds/podvolumerestores.yaml, charts/velero/crds/restores.yaml, charts/velero/crds/schedules.yaml, charts/velero/values.yaml
=> [velero]Bump velero version v1.13.0

.github/workflows/lint-test.yaml
=> [velero] CI test for K8s 1.28 + 1.29

charts/velero/Chart.yaml, charts/velero/templates/deployment.yaml, charts/velero/values.yaml
Fix issue: https://github.com/vmware-tanzu/helm-charts/issues/549
=> [velero] Change default upload type to kopia

.github/PULL_REQUEST_TEMPLATE.md, charts/velero/Chart.yaml, charts/velero/values.yaml
=> [velero]Bump up Velero 1.13.2

charts/velero/Chart.yaml, charts/velero/templates/serviceaccount-server.yaml
=> [velero] fix imagePullSecrets to velero server serviceaccount #595

charts/velero/Chart.yaml, charts/velero/templates/deployment.yaml, charts/velero/values.yaml
=> [velero] feat: Adds --keep-latest-jobs-count for repository maintenance job

.github/workflows/lint-test.yaml
=> chore: add k8s v1.31 CI test

charts/velero/Chart.yaml, charts/velero/values.yaml
=> [velero] Bump image to 1.14.1 and chart to 7.2.0

charts/velero/Chart.yaml, charts/velero/templates/node-agent-daemonset.yaml, charts/velero/values.yaml
=> [velero] feat: allow configuring updateStrategy of node-agent DaemonSet

charts/velero/Chart.yaml, charts/velero/values.yaml
=> [velero] Chart version 8.2.0: update velero to 1.15.1

charts/velero/Chart.yaml, charts/velero/values.yaml
=> [velero] Bump Velero Helm Chart to get v1.15.2

charts/velero/Chart.yaml, charts/velero/templates/schedule.yaml, charts/velero/values.yaml
=> [velero] feat(schedule): support skipImmediately in schedule template

charts/velero/Chart.yaml, charts/velero/README.md, charts/velero/crds/backuprepositories.yaml, charts/velero/crds/backups.yaml, charts/velero/crds/backupstoragelocations.yaml, charts/velero/crds/datadownloads.yaml, charts/velero/crds/datauploads.yaml, charts/velero/crds/deletebackuprequests.yaml, charts/velero/crds/downloadrequests.yaml, charts/velero/crds/podvolumebackups.yaml, charts/velero/crds/podvolumerestores.yaml, charts/velero/crds/restores.yaml, charts/velero/crds/schedules.yaml, charts/velero/crds/serverstatusrequests.yaml, charts/velero/crds/volumesnapshotlocations.yaml, charts/velero/templates/deployment.yaml, charts/velero/values.yaml
=> [velero] feat:add support for v1.16.0 and new parameter

charts/velero/Chart.yaml, charts/velero/OWNERS
=> [velero] remove qiuming-best from owners

charts/velero/Chart.yaml, charts/velero/templates/upgrade-crds/serviceaccount-upgrade.yaml
=> [velero]: update crd service account to add imagePullSecrets block

charts/velero/Chart.yaml, charts/velero/templates/upgrade-crds/serviceaccount-upgrade.yaml, charts/velero/templates/upgrade-crds/upgrade-crds.yaml, charts/velero/values.yaml
=> [velero] Allow override of shell commands in case we are using custom base image

charts/velero/Chart.yaml
Addresses https://github.com/vmware-tanzu/helm-charts/issues/682
=> [velero] Bump major version to reflect breaking change in previous release

charts/velero/Chart.yaml, charts/velero/values.schema.json, charts/velero/values.yaml
This PR contains:
- values.schema.json based on structure of values.yaml and expected fields in the templates
- updated certain fields in values.yaml to comply with the type set
This PR implements the enhancement request put in https://github.com/vmware-tanzu/helm-charts/issues/510
=> [velero] add values.schema.json for velero helm chart

charts/velero/Chart.yaml, charts/velero/values.yaml
=> [velero] Bump version for velero 1.16.1
